# Jetson Orin AGX NixOS Configuration (Traditional - No Flake)
#
# RECOMMENDED FOR FIRST INSTALL - simpler, no flake.nix needed.
# This standalone configuration.nix fetches jetpack-nixos directly.
# You can migrate to flakes later if desired.
#
# Installation:
#   1. Copy this file to /mnt/etc/nixos/configuration.nix
#   2. Run: nixos-install
#   3. Reboot and login as spencer (password: changeme)
#   4. Run: passwd  (to change your password)
#
# Future updates:
#   sudo nixos-rebuild switch
#
{ config, lib, pkgs, ... }:

{
  imports = [
    # Hardware configuration (auto-generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Jetpack NixOS module - fetched from GitHub
    # This downloads the module at evaluation time
    (builtins.fetchTarball {
      url = "https://github.com/anduril/jetpack-nixos/archive/master.tar.gz";
      # Optionally pin to a specific commit for reproducibility:
      # url = "https://github.com/anduril/jetpack-nixos/archive/abc123.tar.gz";
      # sha256 = "sha256:0000000000000000000000000000000000000000000000000000";
    } + "/modules/default.nix")
  ];

  # ==========================================================================
  # JETSON HARDWARE CONFIGURATION
  # ==========================================================================

  hardware.nvidia-jetpack = {
    enable = true;
    som = "orin-agx";           # Options: "orin-agx", "orin-nx", "orin-nano"
    carrierBoard = "devkit";
  };

  # GPU support
  hardware.graphics.enable = true;

  # ==========================================================================
  # BOOTLOADER
  # ==========================================================================

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ==========================================================================
  # NETWORKING
  # ==========================================================================

  networking.hostName = "jetson";
  networking.networkmanager.enable = true;

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];
  };

  # ==========================================================================
  # USER CONFIGURATION
  # ==========================================================================

  users.users.spencer = {
    isNormalUser = true;
    description = "Spencer";
    extraGroups = [ "wheel" "video" "render" "networkmanager" "docker" ];
    initialPassword = "changeme";  # CHANGE after first login: passwd
    openssh.authorizedKeys.keys = [
      # "ssh-ed25519 AAAAC3Nza... your-key-comment"
    ];
  };

  # ==========================================================================
  # SERVICES
  # ==========================================================================

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;
    };
  };

  # ==========================================================================
  # PACKAGES
  # ==========================================================================

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    vim neovim git wget curl htop btop tmux tree
    iproute2 ethtool pciutils usbutils lshw
    gcc gnumake cmake python3
  ];

  # ==========================================================================
  # NIX SETTINGS
  # ==========================================================================

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
      trusted-users = [ "root" "@wheel" ];
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  # ==========================================================================
  # SYSTEM
  # ==========================================================================

  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "us";

  system.stateVersion = "25.11";
}
