# Jetson Orin AGX NixOS Configuration
#
# This file defines your NixOS system.
# Works with both flake-based and traditional (non-flake) setups.
#
{ config, lib, pkgs, inputs ? null, ... }:

{
  imports = [
    # Hardware configuration (auto-generated by nixos-generate-config)
    ./hardware-configuration.nix
  ];

  # ==========================================================================
  # JETSON HARDWARE CONFIGURATION
  # ==========================================================================

  hardware.nvidia-jetpack = {
    enable = true;
    som = "orin-agx";           # Options: "orin-agx", "orin-nx", "orin-nano"
    carrierBoard = "devkit";
    # modesetting.enable = true;  # Enable for Wayland (works on Orin)
  };

  # GPU support - required for display, CUDA, and containers
  hardware.graphics.enable = true;

  # ==========================================================================
  # BOOTLOADER
  # ==========================================================================

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ==========================================================================
  # NETWORKING
  # ==========================================================================

  networking.hostName = "jetson";
  networking.networkmanager.enable = true;

  # Firewall
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];  # SSH
  };

  # ==========================================================================
  # USER CONFIGURATION
  # ==========================================================================

  users.users.spencer = {
    isNormalUser = true;
    description = "Spencer";
    extraGroups = [
      "wheel"           # sudo access
      "video"           # GPU/display access (important for Jetson!)
      "networkmanager"  # Network management
      "docker"          # Docker access (if enabled)
    ];
    initialPassword = "changeme";  # CHANGE THIS after first login with: passwd

    # Add your SSH public key for passwordless login:
    openssh.authorizedKeys.keys = [
      # "ssh-ed25519 AAAAC3Nza... your-key-comment"
    ];
  };

  # ==========================================================================
  # SERVICES
  # ==========================================================================

  # SSH - essential for headless Jetson operation
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;  # Set to false after adding SSH keys
    };
  };

  # ==========================================================================
  # PACKAGES
  # ==========================================================================

  # Allow unfree packages (required for NVIDIA/CUDA)
  nixpkgs.config.allowUnfree = true;

  # System-wide packages
  environment.systemPackages = with pkgs; [
    # Essential CLI tools
    vim
    neovim
    git
    wget
    curl
    htop
    btop
    tmux
    tree

    # Networking tools
    iproute2
    ethtool
    nmap

    # Hardware info
    pciutils
    usbutils
    lshw

    # Development
    gcc
    gnumake
    cmake
    python3
  ];

  # ==========================================================================
  # NIX SETTINGS (Determinate-Nix style)
  # ==========================================================================
  #
  # These settings mirror what Determinate Nix enables by default.
  # On NixOS, we configure nix directly rather than using their installer.
  #

  nix = {
    settings = {
      # Enable flakes and new nix command (Determinate Nix defaults)
      experimental-features = [ "nix-command" "flakes" ];

      # Optimize store automatically
      auto-optimise-store = true;

      # Trust wheel group users
      trusted-users = [ "root" "@wheel" ];

      # Better download experience
      connect-timeout = 5;
      log-lines = 25;
      min-free = 128000000;    # 128MB
      max-free = 1000000000;   # 1GB

      # Fallback when builds fail
      fallback = true;
      warn-dirty = false;
    };

    # Automatic garbage collection
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };

    # Keep build dependencies for development
    extraOptions = ''
      keep-outputs = true
      keep-derivations = true
    '';
  };

  # ==========================================================================
  # SYSTEM SETTINGS
  # ==========================================================================

  # Timezone
  time.timeZone = "America/Los_Angeles";  # Change to your timezone

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Console keymap
  console.keyMap = "us";

  # ==========================================================================
  # OPTIONAL: CONTAINERS (uncomment to enable)
  # ==========================================================================

  # Docker with NVIDIA GPU support
  # virtualisation.docker = {
  #   enable = true;
  #   enableOnBoot = true;
  # };
  # hardware.nvidia-container-toolkit.enable = true;

  # ==========================================================================
  # STATE VERSION - DO NOT CHANGE after initial install
  # ==========================================================================

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # were taken. It's fine to leave this at the first install version.
  system.stateVersion = "25.11";
}
