# Flake configuration for Jetson AGX Orin Developer Kit
#
# Copy this file to /mnt/etc/nixos/flake.nix during installation.
# Then run: nixos-install --flake /mnt/etc/nixos#jetson
#
# Post-install updates:
#   cd /etc/nixos
#   sudo nix flake update
#   sudo nixos-rebuild switch --flake .#jetson

{
  description = "NixOS configuration for Jetson AGX Orin";

  inputs = {
    # matches the autogenerated configuration.nix on device
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

    # Jetpack NixOS - NVIDIA Jetson support
    jetpack.url = "github:anduril/jetpack-nixos/master";
    jetpack.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, jetpack, ... }: {
    nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
      modules = [
        # Jetpack NixOS module (provides hardware.nvidia-jetpack options)
        jetpack.nixosModules.default

        # system configuration
        ./configuration.nix
      ];
    };
  };
}